lang: cs

project:
  output-dir: ./docs
  type: website
  resources:
    - ".nojekyll"
  render:
    - "*.qmd"
    - "!archive/"
    post-render:
    - cp googleb16326ba55692535.html docs/googleb16326ba55692535.html
    
website:
  page-navigation: true
  navbar:
    logo-alt: "Opylovači Handrkov"
    background: rgb(64,	105,	91)
    left:
      - href: index.qmd
        text: "Opylovači Handrkov"
      - href: index.qmd#mise
        text: "Smysl a cíle" 
      - href: index.qmd#prakticke-informace
        text: "Praktické informace"     
      - href: index.qmd#pridejse
        text: "Přidej se!"         
      - href: index.qmd#kontakt
        text: "Kontakt"
    right:
      - icon: github
        href: https://github.com/Pollination-Ecology-Group
      - icon: whatsapp
        href: https://wa.me/420774553734  
  
  page-footer: 
    left: "Made by Jakub Štenc and Quarto" 
    right: 
      - icon: github
        href: https://github.com/Pollination-Ecology-Group
      - icon: whatsapp
        href: https://wa.me/420774553734
  


#  announcement:
#    icon: info-circle
#    dismissable: true
#    content: ""
#    type: light
#    position: below-navbar
#  back-to-top-navigation: true

format:
  html:
    fontsize: 1.15rem
    monofont: Fira Code
    highlight-style: arrow
    css: [custom_theme.scss]
    toc: false
    code-overflow: scroll
    linkcolor: rgb(97,30,30)
    background: #40695B
    toc-depth: 5
    anchor-sections: true
